INSERT INTO meals (name, price) VALUES ('Apple Pie', '10.99')
INSERT INTO meals (name, price) VALUES ('Hunter`s Stew', '12.99')
INSERT INTO meals (name, price) VALUES ('Potato soup', '9.99')
INSERT INTO meals (name, price) VALUES ('Carrot Salad', '8.99')
INSERT INTO meals (name, price) VALUES ('Gingerbread loaf', '11.99')
INSERT INTO meals (name, price) VALUES ('Apple pie', '12.99')
INSERT INTO meals (name, price) VALUES ('Haluski', '13.99')
