INSERT INTO cuisines (name) VALUES ('Polish')
INSERT INTO cuisines (name) VALUES ('Mexican')
INSERT INTO cuisines (name) VALUES ('Italian')

INSERT INTO desserts (name, price, cuisine_id) VALUES ('Ice cream', '3.99', '1')
INSERT INTO desserts (name, price, cuisine_id) VALUES ('Waffles', '4.99', '1')
INSERT INTO desserts (name, price, cuisine_id) VALUES ('Pancakes', '4.99', '1')
INSERT INTO desserts (name, price, cuisine_id) VALUES ('Chocolate Whip', '6.99', '1')
INSERT INTO desserts (name, price, cuisine_id) VALUES ('cream-cookie', '21.99', '1')

INSERT INTO desserts (name, price, cuisine_id) VALUES ('Churros', '13.99', '2')
INSERT INTO desserts (name, price, cuisine_id) VALUES ('Fried ice cream', '9.99', '2')
INSERT INTO desserts (name, price, cuisine_id) VALUES ('Sopapillas', '8.99', '2')
INSERT INTO desserts (name, price, cuisine_id) VALUES ('Caramel Flan', '10.99', '2')

INSERT INTO desserts (name, price, cuisine_id) VALUES ('Classic tiramisu', '21.99', '3')
INSERT INTO desserts (name, price, cuisine_id) VALUES ('Zuccotto', '10.99', '3')
INSERT INTO desserts (name, price, cuisine_id) VALUES ('Affogato chocolate mousse', '10.99', '3')
INSERT INTO desserts (name, price, cuisine_id) VALUES ('Lemon cake', '10.99', '3')

INSERT INTO drinkExtras (name, price) VALUES ('Lemon', '0.99')
INSERT INTO drinkExtras (name, price) VALUES ('Ice cubes', '0.49')

INSERT INTO meals (name, price, cuisine_id) VALUES ('Apple Pie', '10.99', '1')
INSERT INTO meals (name, price, cuisine_id) VALUES ('Hunter`s Stew', '12.99', '1')
INSERT INTO meals (name, price, cuisine_id) VALUES ('Potato soup', '9.99', '1')
INSERT INTO meals (name, price, cuisine_id) VALUES ('Carrot Salad', '8.99', '1')
INSERT INTO meals (name, price, cuisine_id) VALUES ('Gingerbread loaf', '11.99', '1')
INSERT INTO meals (name, price, cuisine_id) VALUES ('Haluski', '13.99', '1')

INSERT INTO meals (name, price, cuisine_id) VALUES ('Meat peppersalad', '19.99', '2')
INSERT INTO meals (name, price, cuisine_id) VALUES ('Guacamole with nachos', '21.49', '2')
INSERT INTO meals (name, price, cuisine_id) VALUES ('Chilaquiles', '18.49', '2')
INSERT INTO meals (name, price, cuisine_id) VALUES ('Pozole', '13.49', '2')
INSERT INTO meals (name, price, cuisine_id) VALUES ('Tostadas', '16.99', '2')
INSERT INTO meals (name, price, cuisine_id) VALUES ('Chiles es nogada', '17.99', '2')

INSERT INTO meals (name, price, cuisine_id) VALUES ('Lagagne Bolognese', '9.99', '3')
INSERT INTO meals (name, price, cuisine_id) VALUES ('Spaghetti Aglia e Olio', '12.99', '3')
INSERT INTO meals (name, price, cuisine_id) VALUES ('Chicken Parmesan', '15.99', '3')
INSERT INTO meals (name, price, cuisine_id) VALUES ('Pesto pasta', '12.99', '3')
INSERT INTO meals (name, price, cuisine_id) VALUES ('Traditional Osso Buco', '18.99', '3')

INSERT INTO drinks (name, price, cuisine_id) VALUES ('Coke', '3.99', '1')
INSERT INTO drinks (name, price, cuisine_id) VALUES ('Fanta', '3.99', '1')
INSERT INTO drinks (name, price, cuisine_id) VALUES ('Sprite', '3.99', '1')
INSERT INTO drinks (name, price, cuisine_id) VALUES ('Water', '0.99', '1')
INSERT INTO drinks (name, price, cuisine_id) VALUES ('Beer', '9.99', '1')
INSERT INTO drinks (name, price, cuisine_id) VALUES ('Whisky', '20.99', '1')
INSERT INTO drinks (name, price, cuisine_id) VALUES ('Vodka', '14.99', '1')

INSERT INTO drinks (name, price, cuisine_id) VALUES ('Raicilla', '8.99', '2')
INSERT INTO drinks (name, price, cuisine_id) VALUES ('Michelada', '7.99', '2')
INSERT INTO drinks (name, price, cuisine_id) VALUES ('Paloma', '5.99', '2')
INSERT INTO drinks (name, price, cuisine_id) VALUES ('Carajillo', '8.99', '2')
INSERT INTO drinks (name, price, cuisine_id) VALUES ('Margarita', '7.99', '2')

INSERT INTO drinks (name, price, cuisine_id) VALUES ('Americano', '7.99', '3')
INSERT INTO drinks (name, price, cuisine_id) VALUES ('Bellini', '5.99', '3')
INSERT INTO drinks (name, price, cuisine_id) VALUES ('Spritz', '12.99', '3')
INSERT INTO drinks (name, price, cuisine_id) VALUES ('Negroni', '10.99', '3')
